services:
  lukittuPostgres:
    container_name: lukittuPostgres
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:16.0-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  lukittuRedis:
    container_name: lukittuRedis
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    ports:
      - '127.0.0.1:6382:6379'

volumes:
  postgres-data:
