services:
  prisma:
    image: node:latest
    env_file: .env
    working_dir: /app
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    networks:
      - lukittu-network
    command: sh -c "npm install -g pnpm && pnpm exec prisma generate && pnpm exec prisma migrate deploy"

networks:
  lukittu-network:
    external: true
