packages:
  - apps/*
  - packages/*

catalogs:
  prisma:
    prisma: ^6.11.0

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
