packages:
  - apps/*
  - packages/*
catalogs:
  prisma:
    prisma: latest
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
