packages:
  - apps/*
  - packages/*

catalogs:
  prisma:
    prisma: ^7.8.0

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry-internal/node-cpu-profiler'
  - '@sentry/cli'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
