services:
  lukittu:
    container_name: lukittu
    image: kassq/lukittu:${IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file: .env
    environment:
      - REDIS_HOST=lukittuRedis
    ports:
      - "127.0.0.1:3069:3000"
    networks:
      - lukittu-network

  lukittuBot:
    container_name: lukittuBot
    image: kassq/lukittu-bot:${IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file: .env
    environment:
      - REDIS_HOST=lukittuRedis
    networks:
      - lukittu-network

  lukittuPostgres:
    container_name: lukittuPostgres
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:16.0-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:5434:5432"
    networks:
      - lukittu-network

  lukittuRedis:
    container_name: lukittuRedis
    image: redis:8-alpine
    restart: unless-stopped
    env_file: .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6382:6379"
    networks:
      - lukittu-network

volumes:
  postgres-data:
    name: lukittu_postgres-data

networks:
  lukittu-network:
    external: true
